# Generated by Django 5.2 on 2025-05-29 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_first_name_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blood_group',
        ),
    ]
