# Generated by Django 5.2 on 2025-05-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allergies',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('nuts', 'Nuts'), ('egg', 'Egg'), ('milk', 'Milk'), ('fish', 'Fish')], max_length=20),
        ),
    ]
