# Generated by Django 5.2 on 2025-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sponsor_email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sponsor_full_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sponsor_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sponsor_relation',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('next-of-kin', 'Next of Kin'), ('guardian', 'Guardian')], max_length=20),
        ),
    ]
