# Generated by Django 5.2 on 2025-06-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
