# Generated by Django 5.2 on 2025-05-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0004_alter_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='patient_purpose',
            field=models.TextField(max_length=20),
        ),
    ]
