# Generated by Django 5.2 on 2025-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='diagnosis',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctor_notes',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctor_result',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='prescription',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
