# Generated by Django 5.2 on 2025-06-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0007_appointments_diagnosis_appointments_doctor_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='patient_matric',
        ),
    ]
