# Generated by Django 5.2 on 2025-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0009_rename_appointment_date_appointments_appointment_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_first_name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_last_name',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
